### ISSUE TITLE
QR Code Card does not support templates

### ISSUE THREAD

**Issue by 13robin37** [igor-panteleev/lovelace-qr-code-card#2]
Hey @igor-panteleev, great card! Currently it doesn't seem to support setting templates for qr codes, e.g. assigning an `input_text` state to the password field or setting it to source type text and rendering a template entity there. Both times the QR code text contains the literal template and not the actual value, e.g. instead of

`S:WIFINAME;T:WPA;P:WIFIPASSWORD;;` it returns
`{{ "S:WIFINAME;T:WPA;P:"~states('input_text.guest_wifi_password')~";;" }}`

Could you entend the functionality by any chance?

**Comment by igor-panteleev** [comment]
I might add support to use entities in the WiFi config alongside string values.
For now, there is a workaround https://github.com/igor-panteleev/lovelace-qr-code-card/issues/4#issuecomment-1502135436
