### ISSUE TITLE
Autogenerate SSID password and update unifi config

### ISSUE THREAD

**Issue by saltyautomation** [igor-panteleev/lovelace-qr-code-card#3]
Wondering if it would be possible to add an option to this card to generate a random password and update a unifi controller with that password. Someone else wrote a script to handle updating the Unifi side. Here is a link to that thread. https://community.home-assistant.io/t/updated-automating-unifi-wifi-ssid-password-changes-and-qr-code-generation/380616

**Comment by igor-panteleev** [comment]
It's possible to call Home Assistant services with a card.
But I would rather not.
It will be better to generate a password on the backend and store it in an entity.
Then use this entity to set a password in Unifi and render the QR code using the card.

Here is a way how to use entity for WiFi config in this card https://github.com/igor-panteleev/lovelace-qr-code-card/issues/4#issuecomment-1502135436
